#!/bin/bash
# Manual cleanup script generated by repository cleanup
# Review each command before executing

echo "Manual Repository Cleanup Actions"
echo "================================"
echo "⚠️  Review each command before executing!"
echo ""

# Branch deletion commands (commented out for safety)
echo "# Delete stale branches (REVIEW FIRST):"

echo ""
echo "# Update outdated packages:"
echo "# npm update  # Update all packages"
echo "# npm audit fix  # Fix security vulnerabilities"

echo ""
echo "# Advanced cleanup (use with caution):"
echo "# git reflog expire --expire=now --all"
echo "# git gc --prune=now --aggressive"

echo ""
echo "Cleanup script completed. Review and execute commands as needed."
