name: Daily AI Usage Report

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  ai-usage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Start server
        run: npm start &

      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Fetch usage (last 30 days)
        run: curl -fS http://localhost:3000/api/admin/openai/usage || echo "Usage endpoint unavailable in CI"
