name: Weekly Dependency Updates

on:
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install npm-check-updates
        run: npm i -g npm-check-updates

      - name: Create update branch
        run: |
          git config user.email "bot@flowvision.local"
          git config user.name "flowvision-bot"
          git checkout -b chore/weekly-dep-updates || git checkout chore/weekly-dep-updates

      - name: Update dependencies (non-major)
        run: ncu -u --target minor

      - name: Install and build
        run: |
          npm ci || npm install
          npm run build

      - name: Commit changes
        run: |
          git add package.json package-lock.json || true
          git commit -m "chore(deps): weekly dependency updates" || echo "No changes"

      - name: Push branch
        run: |
          git push --set-upstream origin chore/weekly-dep-updates || git push origin chore/weekly-dep-updates

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/weekly-dep-updates
          title: 'chore(deps): weekly dependency updates'
          body: 'Automated weekly dependency updates'
          labels: dependencies
