name: Forward repo events to local orchestrator

on:
  issues:
    types: [opened, edited, labeled]
  pull_request:
    types: [opened, reopened, edited, synchronize, labeled]

jobs:
  forward:
    runs-on: ubuntu-latest
    steps:
      - name: Build webhook signature
        id: sig
        env:
          SECRET: ${{ secrets.ORCHESTRATOR_WEBHOOK_SECRET }}
        run: |
          PAYLOAD_FILE=payload.json
          echo '${{ toJson(github.event) }}' > "$PAYLOAD_FILE"
          SIG="sha256=$(printf '%s' "$(cat $PAYLOAD_FILE)" | openssl dgst -sha256 -hmac "$SECRET" | cut -d' ' -f2)"
          echo "signature=$SIG" >> $GITHUB_OUTPUT
          echo "payload_path=$PAYLOAD_FILE" >> $GITHUB_OUTPUT

      - name: POST to orchestrator
        env:
          WEBHOOK_URL: ${{ secrets.ORCHESTRATOR_WEBHOOK_URL }}
        run: |
          if [ -z "$WEBHOOK_URL" ]; then
            echo "WEBHOOK_URL not set; skipping"
            exit 0
          fi
          curl -sS -X POST "$WEBHOOK_URL" \
            -H 'Content-Type: application/json' \
            -H 'X-GitHub-Event: ${{ github.event_name }}' \
            -H 'X-Hub-Signature-256: ${{ steps.sig.outputs.signature }}' \
            --data @${{ steps.sig.outputs.payload_path }}
