name: Stale Issue/PR Triage

on:
  schedule:
    - cron: '0 12 * * 1-5'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 14
          days-before-close: 7
          stale-issue-message: 'This issue has been marked stale due to inactivity.'
          stale-pr-message: 'This PR has been marked stale due to inactivity.'
          close-issue-message: 'Closing due to inactivity.'
          close-pr-message: 'Closing due to inactivity.'
